// Copyright Andrii Berozkin, Inc. All Rights Reserved.

#pragma once

#include <CoreMinimal.h>
#include <NativeGameplayTags.h>



//	Health
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FHealth_OnDeath);

//	Health.Cheats
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FHealth_Cheats_GodMode);

//	GE
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_Damage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_DamagePeriodic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_Heal);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_HealPeriodic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_UpgradeInProgress);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_ProduceBlocked);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_UnitProduce);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_UnitProduceBlocked);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_UnitProducePeriodic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_BuildingUpgradeInProgress);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_MoneyGet);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_MoneyLost);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_MoneyGetPeriodic);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_MoneyLostPeriodic);

//	GameplayCue
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGC_Character_DamageTaken);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGC_UnitShoot);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGC_HeliFlight);

//	Weapons
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_Weapon_NoFire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(FGE_Weapon_HasAnyWeapon);